// <auto-generated />
namespace web_server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class UsersBooks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsersBooks));
        
        string IMigrationMetadata.Id
        {
            get { return "202004271122064_UsersBooks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
